USE DATABASE {{ database }};
USE SCHEMA {{ schema }};

CREATE OR REPLACE EXTERNAL TABLE all_fire_incidents (
  "Incident Number" STRING AS (value:incident_number::STRING),
  "Exposure Number" STRING AS (value:exposure_number::STRING),
  "ID" STRING AS (value:id::STRING),
  "Address" STRING AS (value:address::STRING),
  "Incident Date" TIMESTAMP AS (value:incident_date::TIMESTAMP),
  "Call Number" STRING AS (value:call_number::STRING),
  "Alarm DtTm" TIMESTAMP AS (value:alarm_dttm::TIMESTAMP),
  "Arrival DtTm" TIMESTAMP AS (value:arrival_dttm::TIMESTAMP),
  "Close DtTm" TIMESTAMP AS (value:close_dttm::TIMESTAMP),
  "City" STRING AS (value:city::STRING),
  "zipcode" STRING AS (value:zipcode::STRING),
  "Battalion" STRING AS (value:battalion::STRING),
  "Station Area" STRING AS (value:station_area::STRING),
  "Box" STRING AS (value:box::STRING),
  "Suppression Units" STRING AS (value:suppression_units::STRING),
  "Suppression Personnel" STRING AS (value:suppression_personnel::STRING),
  "EMS Units" STRING AS (value:ems_units::STRING),
  "EMS Personnel" STRING AS (value:ems_personnel::STRING),
  "Other Units" STRING AS (value:other_units::STRING),
  "Other Personnel" STRING AS (value:other_personnel::STRING),
  "First Unit On Scene" STRING AS (value:first_unit_on_scene::STRING),
  "Estimated Property Loss" STRING AS (value:estimated_property_loss::STRING),
  "Estimated Contents Loss" STRING AS (value:estimated_contents_loss::STRING),
  "Fire Fatalities" STRING AS (value:fire_fatalities::STRING),
  "Fire Injuries" STRING AS (value:fire_injuries::STRING),
  "Civilian Fatalities" STRING AS (value:civilian_fatalities::STRING),
  "Civilian Injuries" STRING AS (value:civilian_injuries::STRING),
  "Number of Alarms" STRING AS (value:number_of_alarms::STRING),
  "Primary Situation" STRING AS (value:primary_situation::STRING),
  "Mutual Aid" STRING AS (value:mutual_aid::STRING),
  "Action Taken Primary" STRING AS (value:action_taken_primary::STRING),
  "Action Taken Secondary" STRING AS (value:action_taken_secondary::STRING),
  "Action Taken Other" STRING AS (value:action_taken_other::STRING),
  "Detector Alerted Occupants" STRING AS (value:detector_alerted_occupants::STRING),
  "Property Use" STRING AS (value:property_use::STRING),
  "Area of Fire Origin" STRING AS (value:area_of_fire_origin::STRING),
  "Ignition Cause" STRING AS (value:ignition_cause::STRING),
  "Ignition Factor Primary" STRING AS (value:ignition_factor_primary::STRING),
  "Ignition Factor Secondary" STRING AS (value:ignition_factor_secondary::STRING),
  "Heat Source" STRING AS (value:heat_source::STRING),
  "Item First Ignited" STRING AS (value:item_first_ignited::STRING),
  "Human Factors Associated with Ignition" STRING AS (value:human_factors_associated_with_ignition::STRING),
  "Structure Type" STRING AS (value:structure_type::STRING),
  "Structure Status" STRING AS (value:structure_status::STRING),
  "Floor of Fire Origin" STRING AS (value:floor_of_fire_origin::STRING),
  "Fire Spread" STRING AS (value:fire_spread::STRING),
  "No Flame Spread" STRING AS (value:no_flame_spread::STRING),
  "Number of floors with minimum damage" STRING AS (value:number_of_floors_with_minimum_damage::STRING),
  "Number of floors with significant damage" STRING AS (value:number_of_floors_with_significant_damage::STRING),
  "Number of floors with heavy damage" STRING AS (value:number_of_floors_with_heavy_damage::STRING),
  "Number of floors with extreme damage" STRING AS (value:number_of_floors_with_extreme_damage::STRING),
  "Detectors Present" STRING AS (value:detectors_present::STRING),
  "Detector Type" STRING AS (value:detector_type::STRING),
  "Detector Operation" STRING AS (value:detector_operation::STRING),
  "Detector Effectiveness" STRING AS (value:detector_effectiveness::STRING),
  "Detector Failure Reason" STRING AS (value:detector_failure_reason::STRING),
  "Automatic Extinguishing System Present" STRING AS (value:automatic_extinguishing_system_present::STRING),
  "Automatic Extinguishing Sytem Type" STRING AS (value:automatic_extinguishing_sytem_type::STRING),
  "Automatic Extinguishing Sytem Perfomance" STRING AS (value:automatic_extinguishing_sytem_perfomance::STRING),
  "Automatic Extinguishing Sytem Failure Reason" STRING AS (value:automatic_extinguishing_sytem_failure_reason::STRING),
  "Number of Sprinkler Heads Operating" STRING AS (value:number_of_sprinkler_heads_operating::STRING),
  "Supervisor District" STRING AS (value:supervisor_district::STRING),
  "neighborhood_district" STRING AS (value:neighborhood_district::STRING),
  "longitude" FLOAT AS (value:point.coordinates[0]::FLOAT),
  "latitude" FLOAT AS (value:point.coordinates[1]::FLOAT),
  "data_as_of" TIMESTAMP AS (value:data_as_of::TIMESTAMP),
  "data_loaded_at" TIMESTAMP AS (value:data_loaded_at::TIMESTAMP)
)
LOCATION = @FIRE_INCIDENTS_STAGE
FILE_FORMAT = (FORMAT_NAME = REPORT_INCIDENTS_FORMAT)
AUTO_REFRESH = TRUE;