USE DATABASE {{ database }};
USE SCHEMA {{ schema }};

CREATE OR REPLACE TABLE daily_fire_incidents (
  "Incident Number" STRING ,
  "Exposure Number" STRING ,
  "ID" STRING ,
  "Address" STRING,
  "Incident Date" TIMESTAMP ,
  "Call Number" STRING,
  "Alarm DtTm" TIMESTAMP ,
  "Arrival DtTm" TIMESTAMP ,
  "Close DtTm" TIMESTAMP ,
  "City" STRING ,
  "zipcode" STRING ,
  "Battalion" STRING ,
  "Station Area" STRING ,
  "Box" STRING ,
  "Suppression Units" STRING,
  "Suppression Personnel" STRING ,
  "EMS Units" STRING,
  "EMS Personnel" STRING ,
  "Other Units" STRING ,
  "Other Personnel" STRING ,
  "First Unit On Scene" STRING ,
  "Estimated Property Loss" STRING ,
  "Estimated Contents Loss" STRING ,
  "Fire Fatalities" STRING ,
  "Fire Injuries" STRING ,
  "Civilian Fatalities" STRING ,
  "Civilian Injuries" STRING ,
  "Number of Alarms" STRING,
  "Primary Situation" STRING ,
  "Mutual Aid" STRING ,
  "Action Taken Primary" STRING ,
  "Action Taken Secondary" STRING,
  "Action Taken Other" STRING ,
  "Detector Alerted Occupants" STRING ,
  "Property Use" STRING ,
  "Area of Fire Origin" STRING ,
  "Ignition Cause" STRING ,
  "Ignition Factor Primary" STRING ,
  "Ignition Factor Secondary" STRING ,
  "Heat Source" STRING ,
  "Item First Ignited" STRING ,
  "Human Factors Associated with Ignition" STRING ,
  "Structure Type" STRING ,
  "Structure Status" STRING ,
  "Floor of Fire Origin" STRING ,
  "Fire Spread" STRING ,
  "No Flame Spread" STRING ,
  "Number of floors with minimum damage" STRING ,
  "Number of floors with significant damage" STRING ,
  "Number of floors with heavy damage" STRING ,
  "Number of floors with extreme damage" STRING ,
  "Detectors Present" STRING ,
  "Detector Type" STRING ,
  "Detector Operation" STRING ,
  "Detector Effectiveness" STRING ,
  "Detector Failure Reason" STRING ,
  "Automatic Extinguishing System Present" STRING ,
  "Automatic Extinguishing Sytem Type" STRING ,
  "Automatic Extinguishing Sytem Perfomance" STRING,
  "Automatic Extinguishing Sytem Failure Reason" STRING ,
  "Number of Sprinkler Heads Operating" STRING ,
  "Supervisor District" STRING ,
  "neighborhood_district" STRING ,
  "longitude" FLOAT ,
  "latitude" FLOAT,
  "data_as_of" TIMESTAMP ,
  "data_loaded_at" TIMESTAMP 
);



COPY INTO daily_fire_incidents FROM(
SELECT
  $1:incident_number::STRING AS "Incident Number",
  $1:exposure_number::STRING AS "Exposure Number",
  $1:id::STRING AS "ID",
  $1:address::STRING AS "Address",
  $1:incident_date::TIMESTAMP AS "Incident Date",
  $1:call_number::STRING AS "Call Number",
  $1:alarm_dttm::TIMESTAMP AS "Alarm DtTm",
  $1:arrival_dttm::TIMESTAMP AS "Arrival DtTm",
  $1:close_dttm::TIMESTAMP AS "Close DtTm",
  $1:city::STRING AS "City",
  $1:zipcode::STRING AS "zipcode",
  $1:battalion::STRING AS "Battalion",
  $1:station_area::STRING AS "Station Area",
  $1:box::STRING AS "Box",
  $1:suppression_units::STRING AS "Suppression Units",
  $1:suppression_personnel::STRING AS "Suppression Personnel",
  $1:ems_units::STRING AS "EMS Units",
  $1:ems_personnel::STRING AS "EMS Personnel",
  $1:other_units::STRING AS "Other Units",
  $1:other_personnel::STRING AS "Other Personnel",
  $1:first_unit_on_scene::STRING AS "First Unit On Scene",
  $1:estimated_property_loss::STRING AS "Estimated Property Loss",
  $1:estimated_contents_loss::STRING AS "Estimated Contents Loss",
  $1:fire_fatalities::STRING AS "Fire Fatalities",
  $1:fire_injuries::STRING AS "Fire Injuries",
  $1:civilian_fatalities::STRING AS "Civilian Fatalities",
  $1:civilian_injuries::STRING AS "Civilian Injuries",
  $1:number_of_alarms::STRING AS "Number of Alarms",
  $1:primary_situation::STRING AS "Primary Situation",
  $1:mutual_aid::STRING AS "Mutual Aid",
  $1:action_taken_primary::STRING AS "Action Taken Primary",
  $1:action_taken_secondary::STRING AS "Action Taken Secondary",
  $1:action_taken_other::STRING AS "Action Taken Other",
  $1:detector_alerted_occupants::STRING AS "Detector Alerted Occupants",
  $1:property_use::STRING AS "Property Use",
  $1:area_of_fire_origin::STRING AS "Area of Fire Origin",
  $1:ignition_cause::STRING AS "Ignition Cause",
  $1:ignition_factor_primary::STRING AS "Ignition Factor Primary",
  $1:ignition_factor_secondary::STRING AS "Ignition Factor Secondary",
  $1:heat_source::STRING AS "Heat Source",
  $1:item_first_ignited::STRING AS "Item First Ignited",
  $1:human_factors_associated_with_ignition::STRING AS "Human Factors Associated with Ignition",
  $1:structure_type::STRING AS "Structure Type",
  $1:structure_status::STRING AS "Structure Status",
  $1:floor_of_fire_origin::STRING AS "Floor of Fire Origin",
  $1:fire_spread::STRING AS "Fire Spread",
  $1:no_flame_spread::STRING AS "No Flame Spread",
  $1:number_of_floors_with_minimum_damage::STRING AS "Number of floors with minimum damage",
  $1:number_of_floors_with_significant_damage::STRING AS "Number of floors with significant damage",
  $1:number_of_floors_with_heavy_damage::STRING AS "Number of floors with heavy damage",
  $1:number_of_floors_with_extreme_damage::STRING AS "Number of floors with extreme damage",
  $1:detectors_present::STRING AS "Detectors Present",
  $1:detector_type::STRING AS "Detector Type",
  $1:detector_operation::STRING AS "Detector Operation",
  $1:detector_effectiveness::STRING AS "Detector Effectiveness",
  $1:detector_failure_reason::STRING AS "Detector Failure Reason",
  $1:automatic_extinguishing_system_present::STRING AS "Automatic Extinguishing System Present",
  $1:automatic_extinguishing_sytem_type::STRING AS "Automatic Extinguishing Sytem Type",
  $1:automatic_extinguishing_sytem_perfomance::STRING AS "Automatic Extinguishing Sytem Perfomance",
  $1:automatic_extinguishing_sytem_failure_reason::STRING AS "Automatic Extinguishing Sytem Failure Reason",
  $1:number_of_sprinkler_heads_operating::STRING AS "Number of Sprinkler Heads Operating",
  $1:supervisor_district::STRING AS "Supervisor District",
  $1:neighborhood_district::STRING AS "neighborhood_district",
  $1:point.coordinates[0]::FLOAT AS longitude,
  $1:point.coordinates[1]::FLOAT AS latitude,
  $1:data_as_of::TIMESTAMP AS data_as_of,
  $1:data_loaded_at::TIMESTAMP AS data_loaded_at
FROM
  @FIRE_INCIDENTS_STAGE (FILE_FORMAT => REPORT_INCIDENTS_FORMAT)
);